version: "3.1"

services:
  le-godaddy-dns:
    image: "soloxb/le-godaddy-dns"
    environment:
      GD_KEY: someMagicKey
      GD_SECRET: theCorrespondingSecret
    volumes:
      - /data/certs:/data/certs
      - /data/keys:/data/keys
      - renew_certificates.conf:/data/letsencrypt/renew_certificates.conf
      - cert-data:/data/letsencrypt/dehydrated/certs

volumes:
  cert-data:
